# Site wide configuration

title: " 蔡俊钦个人学习网站"
description: "完成学业课程 提升知识储备"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: zh_TW 
url:
feed:
  path: atom.xml

# Site owner
owner:
  name: caijunqin
  email: 2542639393@qq.com
  twitter: 
  google:
    ad-client:
    ad-slot:
  bio: "蔡俊钦 网络与新媒体学生"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
